2021 AGM
Homebrew/homebrew-governance pull request #17
Opened 2021-02-16 21:17 UTC by GregBrimble

2021-02-16 22:32 UTC, nandahkrishna commented on 2021-agm.md
> +The Homebrew Project Leader will be chosen by holding an [Schulze Condorcet](https://en.wikipedia.org/wiki/Schulze_method) election. This popular method of voting is used by several organizations suc
```suggestion
The Homebrew Project Leader will be chosen by holding a [Schulze Condorcet](https://en.wikipedia.org/wiki/Schulze_method) election. This popular method of voting is used by several organizations such as Wikimedia, Debian and Ubuntu. The single highest-ranked candidate will be elected to become the Project Leader.
```

2021-02-16 22:40 UTC, sjackman requested changes
Thanks for starting this document!

2021-02-16 22:40 UTC, sjackman commented on 2021-agm.md
> +# Homebrew Annaul General Meeting 2021
```suggestion
# Homebrew Annual General Meeting 2021
```

2021-02-16 22:40 UTC, sjackman commented on 2021-agm.md
> +## Voting Mechanism
```suggestion
# Motions
## Motion to adopt the voting system
```

2021-02-16 22:40 UTC, sjackman commented on 2021-agm.md
> +
```suggestion

# Agenda

- Call to order
- Adoption of the agenda
- Project Leader's report
- Project Leadership Committee's report
- Technical Steering Committee's report
- Treasurer's report of the financial statements
- Motion to adopt the voting system
- Election of the Project Leader
- Election of the Project Leadership Committee
- Member presentations
- Adjournment
```

2021-02-16 22:40 UTC, sjackman commented on 2021-agm.md
> +The Homebrew Project Leader will be chosen by holding an [Schulze Condorcet](https://en.wikipedia.org/wiki/Schulze_method) election. This popular method of voting is used by several organizations suc
```suggestion
The Homebrew Project Leader will be chosen by holding an [Schulze Condorcet method](https://en.wikipedia.org/wiki/Schulze_method) election. This popular method of voting is used by several organizations such as Wikimedia, Debian, and Ubuntu. The single highest-ranked candidate, who is preferred over every other candidate in pairwise comparisons, will be elected to become the Project Leader.
```

2021-02-16 22:40 UTC, sjackman commented on 2021-agm.md
> +The Homebrew Project Leadership Committee will be chosen by holding a [Meek Single Transferable Vote (STV)](https://en.wikipedia.org/wiki/Counting_single_transferable_votes#Meek) election. The quota
```suggestion
The Homebrew Project Leadership Committee will be chosen by holding a [Meek Single Transferable Vote (STV)](https://en.wikipedia.org/wiki/Counting_single_transferable_votes#Meek) election. The quota (threshold) of votes for a candidate to be elected will be calculated using the [Droop quota](https://en.wikipedia.org/wiki/Droop_quota).
```

2021-02-17 00:36 UTC, sjackman commented on 2021-agm.md
> +## Motion to adopt the voting system
```suggestion
- Adjournment

# Motions

## Motion to adopt the voting system
```

2021-02-17 00:37 UTC, sjackman approved these changes
Thank you, Greg!

2021-02-17 00:38 UTC, GregBrimble commented on 2021-agm.md
> +## Motion to adopt the voting system
Sorry, forgot to `git add` before making doing those changes. Thanks for catching.

2021-02-17 11:45 UTC, MikeMcQuaid commented on 2021-agm.md
> +- Treasurer's report of the financial statements
Can we put these before the elections? Two reasons:
- the PL/PLC/TSC may want to state things that affect the elections
- the PL/PLC/TSC may not be reelected and might not want to give the same presentation if that's the case 😂

2021-02-18 14:12 UTC, SMillerDev approved these changes

2021-02-18 18:19 UTC, MikeMcQuaid approved these changes

2021-02-19 23:08 UTC, sjackman approved these changes

2021-02-19 23:09 UTC, merged